# Generated by Django 5.0.1 on 2024-04-07 14:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField()),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='Media/')),
            ],
        ),
    ]
