# Generated by Django 5.0.1 on 2024-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDemoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=300)),
                ('mail', models.EmailField(max_length=554)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
