# Generated by Django 5.0.1 on 2024-04-08 06:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_App', '0005_threeeasysteps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeEasyStepsIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField()),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='Media/')),
            ],
        ),
    ]
