# Generated by Django 5.0.1 on 2024-04-08 09:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_App', '0006_threeeasystepsicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField()),
                ('desc_1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('desc_2', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
