# Generated by Django 5.0.1 on 2024-04-08 11:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_App', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('name', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
